### PR TITLE
Fix s3 url from dot to dash

### PR DESCRIPTION
**Pull request by lesaff**

### CODE REVIEW

**Comment by lesaff** [comment]
I am not sure if dash applies to newly created buckets or not. 

Here's a newly uploaded file 
https://s3-us-west-2.amazonaws.com/redstargold/1053/sub-banner.jpg

It returns S3 error when used with dot instead of dash
https://s3.us-west-2.amazonaws.com/redstargold/1053/sub-banner.jpg

**Comment by f-b-g-m** [comment]
That's weird. The [getObjectUrl()](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#_getObjectUrl) method returns the url with a dot, so i think it should be with a dot. Can you check if getObjectUrl() returns with a dash for you?

I don't want to change this unless I'm sure it won't break the other way around.

```
require_once("/path/to/aws-autoloader.php");
$s3 = new \Aws\S3\S3Client([
	"version"     => "latest",
	"region"      => "",
	"credentials" => [
		"key"    => "",
		"secret" => ""
	]]);

$result = $s3->getObjectUrl("bucketName","keyName");
echo $result;
```

**Comment by lesaff** [comment]
`dump($s3->getObjectUrl("redstargold", "1053/sub-banner.jpg"));`
output:
screen shot 2017-02-28 at 6 52 43 pm

`dump($s3->listObjects([ 'Bucket' =>'redstargold']));`
output:
screen shot 2017-02-28 at 6 50 29 pm

**Comment by lesaff** [comment]
I see what's going on. The previous test were done using `us-west-2` buckets and they returned dash.

I just tried a bucket in `us-east-1` and the result was dot.

**Comment by f-b-g-m** [comment]
I think a better approach to this is to use getObjectUrl() to generate the aws url.

```
protected function s3url($event) {
    if($this->localStorage) {
        $event->return = $event->object->url;
    }
    else {
        $this->setS3Client();
        $ssl = ($this->useSSL) ? 'https' : 'http';
        $key = $event->object->page . "/" . $event->object->name;
        if($this->useMyDomain) {
            $objectURL = "{$ssl}://{$this->bucket}/{$key}";
        }
        else {
            $objectURL = $this->s3->getObjectUrl($this->bucket, $key);
        }
        $event->return = $objectURL;
    }
}
```
And delete the domain method.
I'll do it tomorrow. If you want you can update or create a new PR, not sure how it works.

**Pull request closed without merging**
